/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarangaysRouteImport } from './routes/barangays'
import { Route as ComparativeRouteImport } from './routes/comparative'
import { Route as CompendiumRouteImport } from './routes/compendium'
import { Route as CrosstabRouteImport } from './routes/crosstab'
import { Route as DemographicsRouteImport } from './routes/demographics'
import { Route as ExportLogRouteImport } from './routes/export-log'
import { Route as HouseholdsRouteImport } from './routes/households'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as ValidationRouteImport } from './routes/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarangaysRoute = BarangaysRouteImport.update({
  id: '/barangays',
  path: '/barangays',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeRoute = ComparativeRouteImport.update({
  id: '/comparative',
  path: '/comparative',
  getParentRoute: () => rootRouteImport,
} as any)
const CompendiumRoute = CompendiumRouteImport.update({
  id: '/compendium',
  path: '/compendium',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosstabRoute = CrosstabRouteImport.update({
  id: '/crosstab',
  path: '/crosstab',
  getParentRoute: () => rootRouteImport,
} as any)
const DemographicsRoute = DemographicsRouteImport.update({
  id: '/demographics',
  path: '/demographics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLogRoute = ExportLogRouteImport.update({
  id: '/export-log',
  path: '/export-log',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsRoute = HouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barangays': typeof BarangaysRoute
  '/comparative': typeof ComparativeRoute
  '/compendium': typeof CompendiumRoute
  '/crosstab': typeof CrosstabRoute
  '/demographics': typeof DemographicsRoute
  '/export-log': typeof ExportLogRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/inspector': typeof InspectorRoute
  '/persons': typeof PersonsRoute
  '/reports': typeof ReportsRoute
  '/sectors': typeof SectorsRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barangays': typeof BarangaysRoute
  '/comparative': typeof ComparativeRoute
  '/compendium': typeof CompendiumRoute
  '/crosstab': typeof CrosstabRoute
  '/demographics': typeof DemographicsRoute
  '/export-log': typeof ExportLogRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/inspector': typeof InspectorRoute
  '/persons': typeof PersonsRoute
  '/reports': typeof ReportsRoute
  '/sectors': typeof SectorsRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barangays': typeof BarangaysRoute
  '/comparative': typeof ComparativeRoute
  '/compendium': typeof CompendiumRoute
  '/crosstab': typeof CrosstabRoute
  '/demographics': typeof DemographicsRoute
  '/export-log': typeof ExportLogRoute
  '/households': typeof HouseholdsRoute
  '/import': typeof ImportRoute
  '/inspector': typeof InspectorRoute
  '/persons': typeof PersonsRoute
  '/reports': typeof ReportsRoute
  '/sectors': typeof SectorsRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barangays'
    | '/comparative'
    | '/compendium'
    | '/crosstab'
    | '/demographics'
    | '/export-log'
    | '/households'
    | '/import'
    | '/inspector'
    | '/persons'
    | '/reports'
    | '/sectors'
    | '/settings'
    | '/troubleshooting'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barangays'
    | '/comparative'
    | '/compendium'
    | '/crosstab'
    | '/demographics'
    | '/export-log'
    | '/households'
    | '/import'
    | '/inspector'
    | '/persons'
    | '/reports'
    | '/sectors'
    | '/settings'
    | '/troubleshooting'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/barangays'
    | '/comparative'
    | '/compendium'
    | '/crosstab'
    | '/demographics'
    | '/export-log'
    | '/households'
    | '/import'
    | '/inspector'
    | '/persons'
    | '/reports'
    | '/sectors'
    | '/settings'
    | '/troubleshooting'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarangaysRoute: typeof BarangaysRoute
  ComparativeRoute: typeof ComparativeRoute
  CompendiumRoute: typeof CompendiumRoute
  CrosstabRoute: typeof CrosstabRoute
  DemographicsRoute: typeof DemographicsRoute
  ExportLogRoute: typeof ExportLogRoute
  HouseholdsRoute: typeof HouseholdsRoute
  ImportRoute: typeof ImportRoute
  InspectorRoute: typeof InspectorRoute
  PersonsRoute: typeof PersonsRoute
  ReportsRoute: typeof ReportsRoute
  SectorsRoute: typeof SectorsRoute
  SettingsRoute: typeof SettingsRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barangays': {
      id: '/barangays'
      path: '/barangays'
      fullPath: '/barangays'
      preLoaderRoute: typeof BarangaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative': {
      id: '/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ComparativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compendium': {
      id: '/compendium'
      path: '/compendium'
      fullPath: '/compendium'
      preLoaderRoute: typeof CompendiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crosstab': {
      id: '/crosstab'
      path: '/crosstab'
      fullPath: '/crosstab'
      preLoaderRoute: typeof CrosstabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demographics': {
      id: '/demographics'
      path: '/demographics'
      fullPath: '/demographics'
      preLoaderRoute: typeof DemographicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-log': {
      id: '/export-log'
      path: '/export-log'
      fullPath: '/export-log'
      preLoaderRoute: typeof ExportLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households': {
      id: '/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof HouseholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarangaysRoute: BarangaysRoute,
  ComparativeRoute: ComparativeRoute,
  CompendiumRoute: CompendiumRoute,
  CrosstabRoute: CrosstabRoute,
  DemographicsRoute: DemographicsRoute,
  ExportLogRoute: ExportLogRoute,
  HouseholdsRoute: HouseholdsRoute,
  ImportRoute: ImportRoute,
  InspectorRoute: InspectorRoute,
  PersonsRoute: PersonsRoute,
  ReportsRoute: ReportsRoute,
  SectorsRoute: SectorsRoute,
  SettingsRoute: SettingsRoute,
  TroubleshootingRoute: TroubleshootingRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
